//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyConfig
    {
        public int CompanyID { get; set; }
        public string COY { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.Guid> CompanyLogo { get; set; }
        public Nullable<bool> PhoneNumber_IsVisible { get; set; }
        public Nullable<bool> PhoneNumber_IsRequired { get; set; }
        public Nullable<bool> DOB_IsVisible { get; set; }
        public Nullable<bool> DOB_IsRequired { get; set; }
        public Nullable<bool> Location_IsVisible { get; set; }
        public Nullable<bool> Location_IsRequired { get; set; }
        public string EmployeeId_Name { get; set; }
        public Nullable<bool> CustomText1Visible { get; set; }
        public Nullable<bool> CustomText1Required { get; set; }
        public string CustomText1DefName { get; set; }
        public Nullable<bool> CustomText2Visible { get; set; }
        public Nullable<bool> CustomText2Required { get; set; }
        public string CustomText2DefName { get; set; }
        public Nullable<bool> CustomText3Visible { get; set; }
        public Nullable<bool> CustomText3Required { get; set; }
        public string CustomText3DefName { get; set; }
        public Nullable<bool> CustomText4Visible { get; set; }
        public Nullable<bool> CustomText4Required { get; set; }
        public string CustomText4DefName { get; set; }
        public Nullable<bool> CustomText5Visible { get; set; }
        public Nullable<bool> CustomText5Required { get; set; }
        public string CustomText5DefName { get; set; }
        public Nullable<bool> CustomDateTime1Visible { get; set; }
        public Nullable<bool> CustomDateTime1Required { get; set; }
        public string CustomDateTime1DefName { get; set; }
        public Nullable<bool> CustomDateTime2Visible { get; set; }
        public Nullable<bool> CustomDateTime2Required { get; set; }
        public string CustomDateTime2DefName { get; set; }
        public string FileSendFrequency { get; set; }
        public Nullable<bool> AllowUpdate { get; set; }
        public Nullable<bool> AllowDelete { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<System.DateTime> LastExtractionDate { get; set; }
        public Nullable<bool> EnableExtraction { get; set; }
    }
}
