//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Nullable<int> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public System.Guid ParticipantID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Location { get; set; }
        public string CustomText1 { get; set; }
        public string CustomText2 { get; set; }
        public string CustomText3 { get; set; }
        public string CustomText4 { get; set; }
        public string CustomText5 { get; set; }
        public Nullable<System.DateTime> CustomDateTime1 { get; set; }
        public Nullable<System.DateTime> CustomDateTime2 { get; set; }
        public Nullable<System.DateTime> ExtractionDateTime { get; set; }
    }
}
